/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as PeriodsRouteImport } from './routes/periods'
import { Route as ProvisionRouteImport } from './routes/provision'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReviewItemsRouteImport } from './routes/review-items'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as ProvenanceResultIdRouteImport } from './routes/provenance.$resultId'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as RunsRunIdIndexRouteImport } from './routes/runs.$runId.index'
import { Route as RunsRunIdAuditRouteImport } from './routes/runs.$runId.audit'
import { Route as RunsRunIdExportRouteImport } from './routes/runs.$runId.export'
import { Route as RunsRunIdFindingsRouteImport } from './routes/runs.$runId.findings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodsRoute = PeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisionRoute = ProvisionRouteImport.update({
  id: '/provision',
  path: '/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewItemsRoute = ReviewItemsRouteImport.update({
  id: '/review-items',
  path: '/review-items',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvenanceResultIdRoute = ProvenanceResultIdRouteImport.update({
  id: '/provenance/$resultId',
  path: '/provenance/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdAuditRoute = RunsRunIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdExportRoute = RunsRunIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdFindingsRoute = RunsRunIdFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => RunsRunIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/documents': typeof DocumentsRoute
  '/governance': typeof GovernanceRoute
  '/intake': typeof IntakeRoute
  '/mapping': typeof MappingRoute
  '/periods': typeof PeriodsRoute
  '/provision': typeof ProvisionRoute
  '/review': typeof ReviewRoute
  '/review-items': typeof ReviewItemsRoute
  '/workbench': typeof WorkbenchRoute
  '/provenance/$resultId': typeof ProvenanceResultIdRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/$runId/audit': typeof RunsRunIdAuditRoute
  '/runs/$runId/export': typeof RunsRunIdExportRoute
  '/runs/$runId/findings': typeof RunsRunIdFindingsRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/documents': typeof DocumentsRoute
  '/governance': typeof GovernanceRoute
  '/intake': typeof IntakeRoute
  '/mapping': typeof MappingRoute
  '/periods': typeof PeriodsRoute
  '/provision': typeof ProvisionRoute
  '/review': typeof ReviewRoute
  '/review-items': typeof ReviewItemsRoute
  '/workbench': typeof WorkbenchRoute
  '/provenance/$resultId': typeof ProvenanceResultIdRoute
  '/runs/$runId/audit': typeof RunsRunIdAuditRoute
  '/runs/$runId/export': typeof RunsRunIdExportRoute
  '/runs/$runId/findings': typeof RunsRunIdFindingsRoute
  '/runs/$runId': typeof RunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/documents': typeof DocumentsRoute
  '/governance': typeof GovernanceRoute
  '/intake': typeof IntakeRoute
  '/mapping': typeof MappingRoute
  '/periods': typeof PeriodsRoute
  '/provision': typeof ProvisionRoute
  '/review': typeof ReviewRoute
  '/review-items': typeof ReviewItemsRoute
  '/workbench': typeof WorkbenchRoute
  '/provenance/$resultId': typeof ProvenanceResultIdRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/$runId/audit': typeof RunsRunIdAuditRoute
  '/runs/$runId/export': typeof RunsRunIdExportRoute
  '/runs/$runId/findings': typeof RunsRunIdFindingsRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/documents'
    | '/governance'
    | '/intake'
    | '/mapping'
    | '/periods'
    | '/provision'
    | '/review'
    | '/review-items'
    | '/workbench'
    | '/provenance/$resultId'
    | '/runs/$runId'
    | '/runs/$runId/audit'
    | '/runs/$runId/export'
    | '/runs/$runId/findings'
    | '/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/documents'
    | '/governance'
    | '/intake'
    | '/mapping'
    | '/periods'
    | '/provision'
    | '/review'
    | '/review-items'
    | '/workbench'
    | '/provenance/$resultId'
    | '/runs/$runId/audit'
    | '/runs/$runId/export'
    | '/runs/$runId/findings'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/documents'
    | '/governance'
    | '/intake'
    | '/mapping'
    | '/periods'
    | '/provision'
    | '/review'
    | '/review-items'
    | '/workbench'
    | '/provenance/$resultId'
    | '/runs/$runId'
    | '/runs/$runId/audit'
    | '/runs/$runId/export'
    | '/runs/$runId/findings'
    | '/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DocumentsRoute: typeof DocumentsRoute
  GovernanceRoute: typeof GovernanceRoute
  IntakeRoute: typeof IntakeRoute
  MappingRoute: typeof MappingRoute
  PeriodsRoute: typeof PeriodsRoute
  ProvisionRoute: typeof ProvisionRoute
  ReviewRoute: typeof ReviewRoute
  ReviewItemsRoute: typeof ReviewItemsRoute
  WorkbenchRoute: typeof WorkbenchRoute
  ProvenanceResultIdRoute: typeof ProvenanceResultIdRoute
  RunsRunIdRoute: typeof RunsRunIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periods': {
      id: '/periods'
      path: '/periods'
      fullPath: '/periods'
      preLoaderRoute: typeof PeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provision': {
      id: '/provision'
      path: '/provision'
      fullPath: '/provision'
      preLoaderRoute: typeof ProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-items': {
      id: '/review-items'
      path: '/review-items'
      fullPath: '/review-items'
      preLoaderRoute: typeof ReviewItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provenance/$resultId': {
      id: '/provenance/$resultId'
      path: '/provenance/$resultId'
      fullPath: '/provenance/$resultId'
      preLoaderRoute: typeof ProvenanceResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/': {
      id: '/runs/$runId/'
      path: '/'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof RunsRunIdIndexRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/audit': {
      id: '/runs/$runId/audit'
      path: '/audit'
      fullPath: '/runs/$runId/audit'
      preLoaderRoute: typeof RunsRunIdAuditRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/export': {
      id: '/runs/$runId/export'
      path: '/export'
      fullPath: '/runs/$runId/export'
      preLoaderRoute: typeof RunsRunIdExportRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/findings': {
      id: '/runs/$runId/findings'
      path: '/findings'
      fullPath: '/runs/$runId/findings'
      preLoaderRoute: typeof RunsRunIdFindingsRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
  }
}

interface RunsRunIdRouteChildren {
  RunsRunIdAuditRoute: typeof RunsRunIdAuditRoute
  RunsRunIdExportRoute: typeof RunsRunIdExportRoute
  RunsRunIdFindingsRoute: typeof RunsRunIdFindingsRoute
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute
}

const RunsRunIdRouteChildren: RunsRunIdRouteChildren = {
  RunsRunIdAuditRoute: RunsRunIdAuditRoute,
  RunsRunIdExportRoute: RunsRunIdExportRoute,
  RunsRunIdFindingsRoute: RunsRunIdFindingsRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
}

const RunsRunIdRouteWithChildren = RunsRunIdRoute._addFileChildren(
  RunsRunIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  DocumentsRoute: DocumentsRoute,
  GovernanceRoute: GovernanceRoute,
  IntakeRoute: IntakeRoute,
  MappingRoute: MappingRoute,
  PeriodsRoute: PeriodsRoute,
  ProvisionRoute: ProvisionRoute,
  ReviewRoute: ReviewRoute,
  ReviewItemsRoute: ReviewItemsRoute,
  WorkbenchRoute: WorkbenchRoute,
  ProvenanceResultIdRoute: ProvenanceResultIdRoute,
  RunsRunIdRoute: RunsRunIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
